54 add credit usage dashboard for users
jcreek/SvelteKitSaasBoilerplate pull request #99
Opened 2024-11-13 14:54 UTC by jcreek

2024-11-13 15:09 UTC, jcreek commented on src/routes/(user)/credits/+page.svelte
> +</style>
Good point, but not necessary for the MVP. Please create an issue for this for milestone 2.0.0

2024-11-13 15:10 UTC, jcreek commented on src/routes/(user)/credits/+page.svelte
> +	}
Not needed for MVP, create a ticket to do this in milestone 2.0.0

2024-11-13 15:10 UTC, jcreek commented on src/routes/(user)/credits/+page.server.ts
> +
Done

2024-11-13 15:10 UTC, jcreek commented on src/routes/(user)/credits/+page.server.ts
> +export async function load({ locals: { safeGetSession } }) {
Done

2024-11-13 15:16 UTC, jcreek commented on src/routes/(user)/credits/+page.svelte
> +	}
Create an enhancement ticket for this in the 2.0.0 milestone unassigned

2024-11-13 15:20 UTC, jcreek commented
@OllyNicholass this PR is now ready for review :)

2024-11-19 20:14 UTC, OllyNicholass requested changes
Can we add a link to the credits page.
Nice work

2024-11-19 20:55 UTC, OllyNicholass approved these changes

2024-11-19 20:56 UTC, merged